apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: kc.web.resource 
spec: 
  selector: 
    matchLabels: 
      app: kc.web.resource 
  replicas: 1 
  #设置滚动升级策略 
  #Kubernetes在等待设置的时间后才开始进行升级，例如5s 
  minReadySeconds: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      #在升级过程中最多可以比原先设置多出的Pod数量 
      maxSurge: 1 
      #在升级过程中Deployment控制器最多可以删除多少个旧Pod，主要用于提供缓冲时间 
      maxUnavailable: 1 
  template: 
    metadata: 
      labels: 
        app: kc.web.resource 
    spec: 
      #设置的阿里云私有镜像仓库登陆信息的secret(对应k8s下docker-registry-secret.yaml的设置) 
      imagePullSecrets: 
      - name: docker-registry-secret 
      containers: 
        - name: kc.web.resource 
          image: registry.cn-zhangjiakou.aliyuncs.com/kcloudy-netcore/kc.web.resource:1.0.0.1 
          env: 
            - name: env 
              value: Production 
            - name: port 
              value: 9999 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: kc.web.resource 
  labels: 
    svc: kc.web.resource 
spec: 
  type: NodePort 
  selector: 
    app: kc.web.resource 
  ports: 
    - name: http 
      #Service在集群中暴露的端口（用于Kubernetes服务间的访问） 
      port: 9999 
      #Pod上的端口（与制作容器时暴露的端口一致，在微服务工程代码中指定的端口） 
      targetPort: 9999 
      #K8s集群外部访问的端口（外部机器访问） 
      nodePort: 30002 